name: dated
version: 1.0.0
description: A library provides useful extensions for working with DateTime objects.
repository: https://github.com/monzim/dated
topics:
  - datetime
  - date
  - time
  - time-ago
  - extension

environment:
  sdk: ^3.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
